#!/usr/bin/with-contenv bash
CONFIG_PATH="/config"
CONFIG_FILE="slapd.conf"
SOURCE_CONFIG_FILE="/etc/openldap/slapd.conf"

# Test to see if /config exists - echo a warning if it doesn't
if [ -d $CONFIG_PATH ]
then
  # If there's a config file already then don't bother creating a sample
  if [ ! -f $CONFIG_PATH"/"$CONFIG_FILE ] 
  then
    # If /config exists - make sure there isn't already a slapd.conf.sample - echo info if it does
    if [ ! -f $CONFIG_PATH"/"$CONFIG_FILE".sample" ] 
      then
        cp $SOURCE_CONFIG_FILE $CONFIG_PATH"/"$CONFIG_FILE".sample"
        status=$?
        [ $status -eq 0 ] && echo "Copied over a sample "$CONFIG_FILE" from "$SOURCE_CONFIG_FILE || echo "Couldn't copy "$SOURCE_CONFIG_FILE" to "$CONFIG_PATH
    fi
  else
    echo "There's already a config file here"
  fi
else
  echo "There isn't a "$CONFIG_PATH" directory so won't do anything"
fi
