#!/usr/bin/with-contenv bash
CONFIG_PATH="/config"
CONFIG_FILE="slapd.conf"
SOURCE_CONFIG_FILE="/etc/openldap/slapd.conf"

# Test to see if /config exists - echo a warning if it doesn't
if [ -d $CONFIG_PATH ]
then
  # If there's a config file already then don't bother creating a sample
  if [ ! -f $CONFIG_PATH"/"$CONFIG_FILE ] 
  then
    # If /config exists - make sure there isn't already a slapd.conf.sample - echo info if it does
    if [ ! -f $CONFIG_PATH"/"$CONFIG_FILE".sample" ] 
      then
        cp $SOURCE_CONFIG_FILE $CONFIG_PATH"/"$CONFIG_FILE".sample"
        status=$?
        [ $status -eq 0 ] && echo "Copied over a sample "$CONFIG_FILE" from "$SOURCE_CONFIG_FILE || echo "Couldn't copy "$SOURCE_CONFIG_FILE" to "$CONFIG_PATH
    fi
  else
    echo "There's already a config file here"
  fi
else
  echo "There isn't a "$CONFIG_PATH" directory so won't do anything"
fi

# This is an ugly way of doing things but for some reason the run directory was removed as part of Alpine packaging
# It does seem though that /var/lib/openldap/run is the standard location in slapd.conf and slapd won't start if it can't write there
# So I'm creating run - ideally I'd read the configuration file but I'm lazy and just want to get the address book working so might just
# call this technical debt and deal with it later

if [ ! -d /var/lib/openldap/run ]
then
  mkdir /var/lib/openldap/run
fi
